# NUMPY

Numpy are fixed-size

In [1]:
import numpy as np

In [2]:
sales = [0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]

sales_array = np.array(sales)

sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

## Properties

- **ndim** - number of dimensions
- **shape** - size for each dimension
- **size** - number of elements
- **dtype** - data type

In [3]:
type(sales_array)

numpy.ndarray

In [7]:
infos = f"""
ndim: {sales_array.ndim}
shape: {sales_array.shape}
size: {sales_array.size}
dtype: {sales_array.dtype}
"""
print(infos)


ndim: 1
shape: (10,)
size: 10
dtype: int32



In [8]:
array = np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [9]:
array_2d = np.array([range(5), range(5)])
array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [10]:
array_2d + 100

array([[100, 101, 102, 103, 104],
       [100, 101, 102, 103, 104]])

In [11]:
array.shape

(5,)

In [12]:
array_2d.shape

(2, 5)

In [13]:
array.size

5

In [14]:
array_2d.size

10

In [15]:
array_2d.shape

(2, 5)

In [16]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [17]:
array.ndim

1

In [18]:
array_2d.ndim

2

In [19]:
array.dtype

dtype('int32')

In [20]:
array_2d.dtype

dtype('int32')